# Generated by Django 3.2.24 on 2024-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200)),
                ('general_secretary', models.CharField(max_length=200)),
                ('president', models.CharField(max_length=200)),
                ('headquarters', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
