# Generated by Django 3.2.24 on 2024-02-26 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PartyDetails',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
