# Generated by Django 3.2.24 on 2024-02-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240226_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200)),
                ('general_secretary', models.CharField(max_length=200)),
                ('president', models.CharField(max_length=200)),
                ('headquarters', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(null=True)),
                ('product_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
