# Generated by Django 3.2.24 on 2024-02-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_catalog_catalog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='catalog_id',
        ),
    ]
