# Generated by Django 3.2.24 on 2024-02-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_productdetails_catalog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='catalog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.catalog'),
        ),
    ]
