# Generated by Django 3.2.24 on 2024-03-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_productdetails_catalog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=200)),
                ('user_lastname', models.CharField(max_length=200)),
                ('user_mailId', models.CharField(max_length=200)),
                ('user_contact', models.IntegerField(null=True)),
                ('user_address', models.CharField(max_length=200)),
            ],
        ),
    ]
