# Generated by Django 3.2.24 on 2024-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_contact',
            field=models.CharField(max_length=200),
        ),
    ]
