# Generated by Django 3.2.24 on 2024-03-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_orderproductsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductsdetails',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.order'),
        ),
        migrations.AlterField(
            model_name='orderproductsdetails',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.productdetails'),
        ),
    ]
