# Generated by Django 3.2.24 on 2024-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(null=True)),
                ('product_type', models.CharField(max_length=200)),
                ('warrenty', models.BooleanField(null=True)),
            ],
        ),
    ]
