# Generated by Django 3.2.24 on 2024-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingApp', '0002_rename_productdetails_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=200)),
                ('catalog_Desc', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(null=True)),
            ],
        ),
    ]
