# Generated by Django 3.2.24 on 2024-03-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothingApp', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothingApp.user')),
            ],
        ),
    ]
